# Generated by Django 6.0.3 on 2026-03-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmechanic',
            name='service',
            field=models.CharField(default='ac', max_length=20),
        ),
        migrations.AddField(
            model_name='plumbing',
            name='service',
            field=models.CharField(default='plumbing', max_length=20),
        ),
        migrations.AddField(
            model_name='wiring',
            name='service',
            field=models.CharField(default='wiring', max_length=20),
        ),
    ]
