# Generated by Django 6.0.3 on 2026-03-14 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
        ('services', '0002_acmechanic_service_plumbing_service_wiring_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acmechanic',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='acmechanic',
            name='email',
        ),
        migrations.RemoveField(
            model_name='acmechanic',
            name='password',
        ),
        migrations.RemoveField(
            model_name='acmechanic',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='acmechanic',
            name='service',
        ),
        migrations.RemoveField(
            model_name='plumbing',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='plumbing',
            name='email',
        ),
        migrations.RemoveField(
            model_name='plumbing',
            name='password',
        ),
        migrations.RemoveField(
            model_name='plumbing',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='plumbing',
            name='service',
        ),
        migrations.RemoveField(
            model_name='wiring',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='wiring',
            name='email',
        ),
        migrations.RemoveField(
            model_name='wiring',
            name='password',
        ),
        migrations.RemoveField(
            model_name='wiring',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='wiring',
            name='service',
        ),
        migrations.AddField(
            model_name='acmechanic',
            name='ac_mechanic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ac_mechanic', to='provider.provider'),
        ),
        migrations.AddField(
            model_name='plumbing',
            name='plumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plumber', to='provider.provider'),
        ),
        migrations.AddField(
            model_name='wiring',
            name='electrician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electrician', to='provider.provider'),
        ),
    ]
