# Generated by Django 6.0.3 on 2026-03-14 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
        ('services', '0003_remove_acmechanic_name_remove_acmechanic_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmechanic',
            name='ac_mechanic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ac_mechanic_profile', to='provider.provider'),
        ),
        migrations.AlterField(
            model_name='plumbing',
            name='plumber',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plumbing_profile', to='provider.provider'),
        ),
        migrations.AlterField(
            model_name='wiring',
            name='electrician',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiring_profile', to='provider.provider'),
        ),
    ]
