# Generated by Django 6.0.3 on 2026-03-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('service', models.CharField(choices=[('plumbing', 'Plumbing'), ('wiring', 'Wiring'), ('ac', 'AC')], max_length=20)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('password', models.CharField()),
            ],
        ),
    ]
