# Generated by Django 6.0.3 on 2026-03-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_accepted_jobs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accepted_jobs',
        ),
    ]
