# Generated by Django 6.0.3 on 2026-03-15 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_delete_accepted_jobs'),
        ('user', '0009_remove_booking_service_alter_booking_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.booking')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.provider')),
            ],
        ),
    ]
