# Generated by Django 6.0.3 on 2026-03-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_acceptedjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedjobs',
            name='user',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='acceptedjobs',
            name='booking',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='acceptedjobs',
            name='provider',
            field=models.IntegerField(null=True),
        ),
    ]
