# Generated by Django 6.0.3 on 2026-03-15 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_acceptedjobs_user_alter_acceptedjobs_booking_and_more'),
        ('user', '0009_remove_booking_service_alter_booking_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptedjobs',
            name='user',
        ),
        migrations.AlterField(
            model_name='acceptedjobs',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.booking'),
        ),
        migrations.AlterField(
            model_name='acceptedjobs',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.provider'),
        ),
    ]
