# Generated by Django 6.0.3 on 2026-03-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_remove_acceptedjobs_user_alter_acceptedjobs_booking_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcceptedJobs',
        ),
    ]
