# Generated by Django 6.0.3 on 2026-04-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_delete_acceptedjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='provider_photos/'),
        ),
    ]
