# Generated by Django 6.0.3 on 2026-04-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0008_provider_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
