# Generated by Django 6.0.3 on 2026-05-05 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_booking_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'Phone number must be between 10 and 15 digits.')]),
        ),
    ]
